version: '3'
services:
  app:
    build: .
    restart: on-failure
    env_file:
     - ./.env
  postgres:
    image: postgres:9-alpine
    restart: always
    env_file:
     - ./.env
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
      - ./data/pgsql/config:/etc/postgresql
      - ./data/pgsql/logs:/var/log/postgresql/
    ports:
      - 5432:5432
  admin:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 10000:8081
  elasticsearch:
    image: elastic/elasticsearch:6.2.4
    restart: always
    env_file:
     - ./.env
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    env_file:
     - ./.env
    ports:
      - 10001:5601
    links:
      - elasticsearch

