version: '3'
services:
  app:
    build: .
    restart: always
    env_file:
     - ./.env
  db:
    image: postgres:9-alpine
    restart: always
    volumes:
      - ./data/pgsql:/var/lib/postgresql
    env_file:
     - ./.env
    ports:
      - 5432:5432
  es:
    image: elastic/elasticsearch:6.2.4
    restart: always
    volumes:
      - ./data/elastic
    env_file:
      - ./.env
